import '@styles/globals.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// TODO: idk what is this. research
const inter = Inter({ subsets: ['latin'] })

// TODO: normal metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
